# Generated by Django 4.1.1 on 2022-10-24 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.FloatField()),
                ('trade_wallet_percent', models.FloatField()),
                ('leverage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='symbols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
