# Generated by Django 4.1.1 on 2022-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceExchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='min_qty',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='symbol',
            name='step_size',
            field=models.FloatField(default=0.001),
        ),
    ]
