# Generated by Django 4.1.1 on 2022-10-12 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='users',
            field=models.ManyToManyField(related_name='symbols', to=settings.AUTH_USER_MODEL),
        ),
    ]
